# Generated by Django 5.1.6 on 2025-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usercam_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="address",
            field=models.TextField(default="N/A"),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="age",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="dob",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Other",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="occupation",
            field=models.CharField(default="Unemployed", max_length=100),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="email",
            field=models.EmailField(default="noemail@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="photo",
            field=models.ImageField(default="photos/default.png", upload_to="photos/"),
        ),
    ]
